services:
  db:
    image: alessraia/aemmeis_dependability-db:main
    platform: linux/amd64
    container_name: aemmetsw-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Europe/Rome
    ports:
      - "3307:3306"    # opzionale, ma utile se vuoi collegarti da MySQL Workbench
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 48
      start_period: 10s
    restart: unless-stopped

  app:
    image: alessraia/aemmeis_dependability:main
    platform: linux/amd64
    container_name: aemmetsw-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "aemmetsw-db"     # questo Ã¨ il nome del servizio db qui sopra
      DB_PORT: "3306"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TZ: Europe/Rome

# Definizione del volume
volumes:
  dbdata:
