version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: aemmetsw-db
    environment:
      MYSQL_ROOT_PASSWORD: "RootDocker_123!"
    ports:
      - "3307:3306"    # opzionale, ma utile se vuoi collegarti da MySQL Workbench
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pRootDocker_123!"]
      interval: 5s
      timeout: 3s
      retries: 48
      start_period: 10s
    restart: unless-stopped

  app:

    image: alessraia/aemmeis_dependability:main
    container_name: aemmetsw-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "db"     # questo Ã¨ il nome del servizio db qui sopra
      DB_PORT: "3306"
      DB_NAME: "aemmetsw"
      DB_USER: "root"
      DB_PASS: "RootDocker_123!"

